// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}

export class DashboardSummary {
    /**
     * Creates a new DashboardSummary instance.
     * @param {Partial<DashboardSummary>} [$$source = {}] - The source object to create the DashboardSummary.
     */
    constructor($$source = {}) {
        if (!("lastNightUsage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastNightUsage"] = "";
        }
        if (!("ahi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ahi"] = 0;
        }
        if (!("leak95" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["leak95"] = 0;
        }
        if (!("pressure95" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pressure95"] = 0;
        }
        if (!("importedNightCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["importedNightCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DashboardSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DashboardSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DashboardSummary(/** @type {Partial<DashboardSummary>} */($$parsedSource));
    }
}
